//=========================================================
// src/Feladat2_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$


#define BTN0 P0_B2
#define LED0 P1_B4
#define PAUSE 30
//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------

uint8_t counter = 0;
void SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}

void Delay(uint8_t pause){
   while(counter < pause); 
   counter = 0;
}

void Pattern_S(){
  uint8_t i;
  for(i = 0; i < 3; i++){
        LED0 = 0;
        Delay(25);
        LED0 = 1;
        Delay(25);
  }
}
void Pattern_O(){
  uint8_t i;
  for(i = 0; i < 3; i++){
         LED0 = 0;
         Delay(75);
         LED0 = 1;
         Delay(25);
   }
}

void Sos(){
  Pattern_S();
  Delay(25);
  Pattern_O();
  Delay(25);
  Pattern_S();
}
//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main (void)
{
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET();

  while (1) 
  {

    Sos();
    Delay(200);
  }                             
}
