//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8BB1_Register_Enums.h>

#define LED0 P1_B4
#define REACT_TIME 200 //200 ms time for the user's reaction
//-----------------------------------------------------------------------------
// TIMER0_ISR
//-----------------------------------------------------------------------------
//
// TIMER0 ISR Content goes here. Remember to clear flag bits:
// TCON::TF0 (Timer 0 Overflow Flag)
//
//-----------------------------------------------------------------------------
extern uint8_t counter;
extern volatile bit start;
extern volatile bit stop;

SI_INTERRUPT (TIMER0_ISR, TIMER0_IRQn)
{
    TCON_TF0 = 0;
    if(start && !stop)
    {
        counter++;
        if(counter > REACT_TIME)
        {
            stop = 1;
            LED0 = 0; //keep LED0 on
        }
    }
}

