//=========================================================
// src/Feladat1_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8BB1_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$

#define LED0 P1_B4
#define BTN0 P0_B2
//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------

volatile uint8_t counter = 0U; //using 16 bit value, in case of 8 bytes 256 is the max value
volatile bit start = 0;
volatile bit stop = 0;

//simple software delay
void Delay(){
    uint16_t i, j;
    for (i = 0; i < 1000; i++){
       for (j = 0; j < 500; j++);
    }

}

void SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main (void)
{
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET();
  Delay(); //delay
  LED0 = 0; //turn on LED0
  start = 1;
  while (1) 
  {
      if(!stop) //if the passed time is smaller than 200ms
      {
          IE_EA = 0; //enter critical section
          if (BTN0 == 0) //if the button is pressed in time
          {
              LED0 = 1; //turn off the LED0
              stop = 1; //stop the game
          }
          IE_EA = 1; //leave critical section
      }

   }

 }


